mathtutor/urls.py
from django.conf.urls import url
from mathtutor import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'mathtutor/registration/login.html'}, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}, name="logout"),
    url(r'^noaccess/$', views.noaccess, name='noaccess'),
    url(r'^accounts/profile/$', views.parent_survey, name="info"),
    url(r'^accounts/grid/$', views.dashboard, name='dashboard'),
    url(r'^post-surveys/$', views.post_surveys, name="post_surveys"),
    url(r'^lore/(?P<category>[a-z]*)/$', views.quiz_or_practice, name="quiz_or_practice"),
    url(r'^(?P<category>[a-z]*)/quizes/$', views.list_quizes, name="list_quizes"),
    url(r'^learn/(?P<category>[a-z]*)/(?P<which>[a-z]*)/$', views.practice, name="practice"),
    url(r'^learn/(?P<category>[a-z]*)/(?P<which>[a-z]*)/(?P<itemId>\d+)/$', views.practice, name="practice_item"),
    url(r'^(?P<group>\d+)/glossary/$', views.glossary, name="glossary"),
    url(r'^glossary-item/(?P<item_id>\d+)/$', views.glossary, name="glossary_item"),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'', include('mathtutor.urls', namespace='m')),
    url(r'', include('rest_api.urls'))
]

mathtutor/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from codecs import encode
import datetime
from django.utils import timezone
# Create your models here.

class Constants:


    investment_time = datetime.timedelta(days=9, hours=6, minutes=59)

    start_date = {
        '170': timezone.make_aware(datetime.datetime(2015, 10, 15, 8, 00), timezone.get_current_timezone()),
        '153': timezone.make_aware(datetime.datetime(2015, 10, 15, 8, 00), timezone.get_current_timezone()),
        '000': timezone.make_aware(datetime.datetime(2016, 12, 05, 16, 00), timezone.get_current_timezone()),
        '152b': timezone.make_aware(datetime.datetime(2016, 10, 14, 16, 00), timezone.get_current_timezone()),
        '152cp': timezone.make_aware(datetime.datetime(2016, 10, 27, 16, 00), timezone.get_current_timezone()),
        '152cm': timezone.make_aware(datetime.datetime(2016, 10, 28, 16, 00), timezone.get_current_timezone()),
        '152b2': timezone.make_aware(datetime.datetime(2016, 12, 8, 16, 00), timezone.get_current_timezone()),
        '152cm2': timezone.make_aware(datetime.datetime(2017, 1, 11, 16, 00), timezone.get_current_timezone()),
        '152cp2': timezone.make_aware(datetime.datetime(2017, 1, 12, 16, 00), timezone.get_current_timezone()),
        '152b3':  timezone.make_aware(datetime.datetime(2017, 3, 7, 16, 00), timezone.get_current_timezone()),
        '152cp3': timezone.make_aware(datetime.datetime(2017, 3, 28, 16, 00), timezone.get_current_timezone()),
        '152cm3': timezone.make_aware(datetime.datetime(2017, 4, 5, 16, 00), timezone.get_current_timezone()),
        '152b4': timezone.make_aware(datetime.datetime(2017, 5, 4, 16, 00), timezone.get_current_timezone()),
        '152cp4': timezone.make_aware(datetime.datetime(2017, 5, 11, 16, 00), timezone.get_current_timezone()),
        '152cm4': timezone.make_aware(datetime.datetime(2017, 5, 17, 16, 00), timezone.get_current_timezone()),

    }


    contracts = [
        {'base': 15, 'marginal': .75},
        {'base': 10, 'marginal': 1.0},
        {'base': 5, 'marginal': 1.25},
        {'base': 10, 'marginal': 1.50},
    ]

    parent_forms = [
        dict(name='address', qid="SV_57w2e5guFd4fVWd"),
        dict(name='english', qid="SV_3lBaQupuc8gJjHn"),
        dict(name="spanish", qid="SV_6Dqs31d6DOmNaol"),
    ]

    def accessBools(self, district):
        today = timezone.make_aware(datetime.datetime.now(), timezone.get_current_timezone())
        boolList = []
        for x in range(5):
            lower = self.start_date[district] + (timezone.timedelta(7) * x)
            upper = self.start_date[district] + (timezone.timedelta(7) * (x+1))
            boolList.append(dict(available=lower <= today, date=lower))
        boolList.append(dict(available=True, date=today))
        return boolList

    learnTypes = [
        dict(key='def', name='Math Glossary' ),
        dict(key='vid', name="Web Videos with the Awesome Math Guy" ),
        dict(key='tut', name="Practice Questions w/Solution"),
    ]

    categories = {
        1:{
            'oat': 'Arithmetic and Patterns',
            'nobt': 'Big Numbers',
            'nof': 'Fractions',
            'md': 'Measurement and Data',
            'geom': 'Geometry',
            'gen': 'General',
        },
        2:{
            'eat': 'Algebraic Thinking',
            'fpr': 'Proportions and Relationships',
            'mp': 'Measurement and Data',
            'ns': 'Number System',
            'geom': 'Geometry',
            'gen': 'General',
        },
        3:{
            'ee': 'Expressions and Equations',
            'pr': 'Proportions and Relationships',
            'sp': 'Probability and Statistics',
            'ns': 'Number System',
            'geom': 'Geometry',
            'gen': 'General',
        },
        25:[
            dict(key='ns', name='Number System'),
            dict(key='ee', name='Expressions and Equations'),
            dict(key='pr', name='Proportions and Relationships'),
            dict(key='geom', name='Geometry'),
            dict(key='sp', name='Probability and Statistics'),
            dict(key='gen', name="General"),
        ],
    }

    def check_access(self, group, district, category):
        x = 0
        for item in self.categories[group]:
            if item['key'] == category:
                break
            else:
                x+=1
        return self.accessBools(district)[x]['available']


class Student(models.Model):

    stuid = models.OneToOneField(User)
    group = models.IntegerField('Group', default=0)
    treatment = models.CharField('Treatment', max_length=64)
    score = models.CharField('Test Score', max_length=8)
    percentile = models.CharField("Scored Higher", max_length=8)
    assent = models.IntegerField('Student Assent', default=0)
    consent = models.IntegerField('Parent Consent', default=0)
    district = models.CharField("District", max_length=8)

    def set_null_theme(self):
        if not hasattr(self.theme, 'abbrv'):
            print "setting null theme"
            self.theme = Theme.objects.get(abbrv="NOTHEME")
            self.save(update_fields=['theme'])

    def access_date(self):
        return Constants.start_date[self.district]

    def check_access(self):
        start = self.access_date()
        end = start + Constants.investment_time
        now = timezone.localtime(timezone.now())
        endBool = now > end
        partialAccess = start <= now
        fullAccess = start <=  now and now < end
        return dict(full=fullAccess, partial=partialAccess, end=end, endBool=endBool)

    def get_remaining_time(self):
        access_date = self.access_date()
        end_date = access_date + Constants.investment_time
        remaining = end_date - timezone.make_aware(datetime.datetime.now())
        days = int(remaining.days)
        hours = float(remaining.seconds)/3600
        return dict(nights=days+1, days=days, hours=hours, end_date=end_date)

    def get_quiz_progress(self, cat=None):
        u = User.objects.get(id=self.stuid_id)
        qg = QuizGroup.objects.get(group=str(self.group))
        if cat == None:
            total = qg.quiz_set.filter(site="math").count()
            rs = u.result_set.filter(quiz__site="math")
            passed = rs.exclude(quiz__q_category="amc").filter(score__gte=5).order_by('quiz').distinct('quiz').count()
            brainBendersPassed = rs.filter(quiz__q_category="amc").filter(score__gte=3).order_by('quiz').distinct('quiz').count()
            passed += brainBendersPassed
        else:
            score = 5 if cat != "amc" else 3
            total = qg.quiz_set.filter(site="math").filter(q_category=cat).count()
            rs = u.result_set.filter(quiz__site="math").filter(quiz__q_category=cat)
            passed = rs.filter(score__gte=score).order_by('quiz').distinct('quiz').count()

        test_completion = 100 * (float(passed)/total)
        return dict(
            testCompletion=test_completion,
            numberOfQuizes=total,
            passed=passed,
        )

    def check_parent_form_completion(self):
        u = User.objects.get(id=self.stuid_id)
        rs = u.parentformresult_set.all()
        results = {}
        for f in Constants.parent_forms:
            result = rs.filter(qualtrics_id=f['qid']).filter(completeBool=1)
            if result.count() > 0:
                results[f['name']] = True
            else:
                results[f['name']] = False
        return results



    def get_wage_rate(self):
        return Constants.contracts[int(self.treatment)-1]

    def get_wage_info(self):
        quizes = QuizGroup.objects.get(group=str(self.group))
        numberOfQuizes = quizes.quiz_set.filter(site='math').count()
        rate = self.get_wage_rate()
        possibleWage = rate['base'] + float(numberOfQuizes) * rate['marginal']
        quiz_progress = self.get_quiz_progress()
        if quiz_progress['passed'] < 2:
            earnedWage = 0
        else:
            earnedWage = rate['base'] + quiz_progress['passed'] * rate['marginal']
        wageCompletion = 100 * float(earnedWage)/possibleWage
        return dict(earned=earnedWage, completion=wageCompletion, potential=possibleWage)

class Quiz(models.Model):
    q_id = models.CharField("Quiz ID", max_length=256)
    q_name = models.CharField("Quiz Name", max_length=256)
    q_group = models.ForeignKey("QuizGroup", blank=True, null=True)
    q_category = models.CharField('Category', max_length=8)
    site = models.CharField("Website", max_length=16, default='math')

    def get_display_name(self):
        if '_G2_' in self.q_name:
            name = "Beginner"
        elif '_G3_' in self.q_name:
            name = "Intermediate"
        else:
            name = False
        return name

    def get_url(self):
        return "http://ssd.az1.qualtrics.com/SE/?SID={}".format(self.q_id)

    def get_results(self, user):
        rs = user.result_set.filter(quiz__q_id=self.q_id)
        if rs.count() > 0:
            score_list = []
            for r in rs:
                score_list.append(encode(r.score, 'utf-8'))
                score_list.sort(reverse=True)
            attempted = True
            highScore = int(score_list[0])
            numberOfQuestions = 6 if self.q_category != "amc" else 4
            percentScore = 100 * (float(highScore) / numberOfQuestions)
            attempts = rs.count()
            scoreNeeded = 5 if self.q_category != "amc" else 3
            if highScore >= scoreNeeded:
                quizPassed = True
            else:
                quizPassed = False
        else:
            attempted = False
            highScore = False
            percentScore = False
            attempts = 0
            quizPassed = False

        return dict(
            attempted=attempted,
            highScore=highScore,
            percentScore=percentScore,
            attempts=attempts,
            quizPassed=quizPassed,

mathtutor/views.py
from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import auth
from .models import Constants, Quiz, QuizGroup, SubCategory, LearnItem
from django.utils import timezone
from django.http import HttpResponseRedirect
from mathtutor.decorators import check_category_access

constants = Constants()
# Create your views here.

def partial_access_check(user):
    return user.student.check_access()['partial']

def full_access_check(user):
    return user.student.check_access()['full']

@login_required(login_url='/login/')
def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('m:info'))
    else:
        return render(request, 'login.html',)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('m:index'))

def noaccess(request):
    activation = request.user.student.access_date()
    end_date = activation + Constants.investment_time
    end_date_bool = timezone.localtime(timezone.now())
    if timezone.localtime(timezone.now()) < activation:
        auth.logout(request)
        context = {
            'activation': activation,
            'end_date_bool': end_date_bool,
            'tooSoon': True,
            "Constants": Constants,
        }
        return render(request, "mathtutor/registration/noaccess.html", context)
    else:
        return HttpResponseRedirect(reverse('m:index'))

@login_required
@user_passes_test(full_access_check, login_url="/noaccess/", redirect_field_name=None)
def dashboard(request):
    student = request.user.student
    categories = Constants.categories[student.group]
    for c in categories:
        c['results']=student.get_quiz_progress(c['key'])
    context = {
        'student': student,
        'categories': categories,
        "Constants": Constants,
    }
    return render(request, 'mathtutor/dashboard.html', context)

def post_surveys(request):
	pass

@login_required
@user_passes_test(full_access_check, login_url="/noaccess/", redirect_field_name=None)
def quiz_or_practice(request, category):
    student = request.user.student
    context = {
        'student': student,
        'category': filter(lambda c: c['key']==category, Constants.categories[student.group]),
        'Constants': Constants,
    }
    return render(request, 'mathtutor/quiz_or_practice.html', context)

@login_required
@user_passes_test(full_access_check, login_url="/noaccess/", redirect_field_name=None)
def list_quizes(request, category):
    student = request.user.student
    quizGroup = QuizGroup.objects.get(group=student.group)
    quizListObjects = quizGroup.quiz_set.filter(q_category=category)
    quizList = quizListObjects.values()
    for quizObj in quizListObjects:
        results = quizObj.get_results(request.user)
        name = quizObj.get_display_name()
        quiz = filter(lambda q: q['q_id']==quizObj.q_id, quizList)[0]
        quiz['display_name'] = name
        quiz['results'] = results
        quiz['url'] = quizObj.get_url()
    context = {
        'student': student,
        'category': filter(lambda c: c['key']==category, Constants.categories[student.group]),
        'quizList': quizList,
        "Constants": Constants,
    }
    return render(request, "mathtutor/quiz_list.html", context)


@login_required
@user_passes_test(full_access_check, login_url="/noaccess/", redirect_field_name=None)
def practice(request, category, which, itemId=None):
    student = request.user.student
    quizGroup = QuizGroup.objects.get(group=student.group)
    learnItems = []
    for subCategory in SubCategory.objects.all():
        learnItems.append(subCategory.get_list_of_items(quizGroup, category, which))
    context = {
        'student': student,
        'category': filter(lambda c: c['key']==category, Constants.categories[student.group]),
        'learnItems': learnItems,
        "Constants": Constants,
        }
    if itemId == None:
        return render(request, "mathtutor/practice_list.html", context)
    else:
        context['learnItem'] = LearnItem.objects.get(id=itemId)
        return render(request, "mathtutor/practice_item.html", context)

@login_required
@user_passes_test(partial_access_check, login_url="/noaccess/", redirect_field_name=None)
def parent_survey(request):
    url = "http://ssd.az1.qualtrics.com/SE/?SID="
    context = {
        'user': request.user,
        'student': request.user.student,
        'parent_address_form': url + Constants.parent_forms[0]['qid'],
        'parent_survey_english': url + Constants.parent_forms[1]['qid'],
        'parent_survey_spanish': url + Constants.parent_forms[2]['qid'],
    }
    return render_to_response('mathtutor/info.html', context)

def glossary(request, itemId=None):
	pass

mathtutor/templates/mathtutor/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <title>UProgram Math</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.circliful.css' %}">
    <link rel="stylesheet" href="{% static 'css/chelsea.css' %}">
    <link rel="stylesheet" href="{% static 'css/roboto.css' %}">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>

<body>
        {% include "mathtutor/includes/topnav.html" %}
        <div class="container" style="padding-top: 70px; padding-bottom: 30px;">
            <h2 style="font-family: 'Chelsea Market', cursive;">{% block title %}UProgram Math{% endblock %}</h2>
            <div class="row">
            {% if user.is_authenticated %}
                {% include "mathtutor/includes/progressbox.html" %}
            {% endif %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
{% include "mathtutor/includes/footer.html" %}
</body>
<script>
        $(document).ready(function () {
            $('.panelHeading').click(function (e) {
                e.stopPropagation();
                    var $sliderContent = $(this).next('.panelBody'),
                        $panelBody = $(this).closest('.panel-group').find('.panel-body');
                        $panelBody.not($sliderContent.slideToggle("400",changeInnerState)).find('.panel-body:visible').addBack().slideUp();
             });
        });
        function changeInnerState() {
                    var $this = $(this);
                    if ($this.is(':hidden')) $this.find('.panel-body').slideUp();
        }
</script>

<!-- Goolge Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68947688-2', 'auto');
  ga('send', 'pageview');

</script>
</html>

mathtutor/templates/mathtutor/dashboard.html
{% extends 'mathtutor/base.html' %}
{% block title %}UProgram Math{% endblock %}
{% block content %}
<div class="col-md-8 col-md-pull-4">
<div class="thumbnails">
<div class="row">
{% for category in categories %}
{% if forloop.counter == 4 %}
</div>
<div class="row">
{% endif %}
    <div class="col-sm-4">
        <a href="{% url 'm:quiz_or_practice' category.key %}" class="Thumb_{{ category.key }} thumbnail" style="font-weight: bold;">{{ category.name }}
            <hr>
        <p style="font-weight: normal; line-height: 1em">Quiz Progress</p>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="{{ category.results.testCompletion }}" aria-valuemin="0" aria-valuemax="{{ category.results.numberOfQuizes }}" style="width: {{ category.results.testCompletion }}%">
                {{ category.results.passed }}
            </div>
        </div>
        <p style="font-weight: normal">Total Quizzes <span class="badge">{{ category.1.results.numberOfQuizes }}</span></p>{% if category %}</a>{% else %}</span>{% endif %}
    </div>
{% endfor %}
</div>

{% include "mathtutor/includes/reminders.html" %}
</div>
{% endblock %}

mathtutor/templates/mathtutor/info.html
{% extends 'mathtutor/base.html' %}

{% block content %}
<script>
$(document).ready(function() {
	$('#id_username').tooltip();
	});

$(document).ready(function() {
		$('.custom-badge').tooltip();
		});
</script>

<!-- FOR LIVE SITE UNCOMMENT -->
<div class="col-md-8 col-md-pull-4">
{% if not student.check_access.endBool %}
{% include "mathtutor/includes/accessalert.html" %}
{% endif %}
{% if student.check_access.endBool %}
	{% if user.student.district == "170" or user.student.district == "153" %}
		<div class="alert alert-info">
			<p><b>HEADS UP:</b> Still looking to sharpen your math skills? Check out <a href="http://chicagomathtutor.org">ChicagoMathTutor.org</a>!</p>
		</div>
	{% endif %}
<div class="alert alert-notlive">
	<p>The 10 days of Chicago Math Game have concluded.  Make sure your payment information is up to date by logging in again and following the links.  Additionaly, be sure to have you parents fill out a parent survey.</p>
	<p>Thanks for playing!</p>
</div>
{% else %}
<div class="alert alert-green">
    <a href="{% url 'm:dashboard' %}" style="color: white;"><span style="font-weight: bold; font-family: 'Chelsea Market',  cursive; font-size: large;">Continue to Site </span>to start earning!</a>
</div>
{% endif %}

<div class="alert btn-info">
    <a href="{{ parent_address_form }}" style="color: white; font-weight: bold">CLICK HERE TO VERIFY YOUR PAYMENT INFORMATION</a>{% if student.check_parent_form_completion.address %}<span id="success" style="float:right;" class="custom-badge" data-toggle='tooltip' data-placement="right" data-title="Verified!"><span class="glyphicon glyphicon-thumbs-up" style="font-size:large;" aria-hidden="true"></span></span>{% endif %}
</div>

{% if student.check_parent_form_completion.address %}
<div class="alert btn-info">
	 <p><b>PARENTS: TAKE THE PARENT SURVEY AND ENTER A DRAWING FOR ONE OF 10 GIFT CARDS FOR $200</b></p>
	<p><a href="{{ parent_survey_english }}" style="color: white; font-weight: bold;">Survey in English</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{{ parent_survey_spanish }}" style="color: white; font-weight: bold;">Survey in Spanish</a></p>
{% else %}
<div class="alert alert-notlive">
    <a href="#" style="font-weight: bold; color: #949494;" data-container="body" data-toggle="popover" data-placement="top" data-content="">PARENTS: CLICK HERE TO TAKE THE PARENT SURVEY AND ENTER A DRAWING FOR ONE OF 10 GIFT CARDS FOR $200</a>
    <p style="color: #ff2f2f; font-style: italic"><br>Complete the payment information survey in order to access the parent survey.  If you've completed the payment verification, please allow up to 10 minutes for the site to update.</p>
{% endif %}
    <p><br>Parents may enter once for each child that participated in the UChicago Learn and Earn Math Activity.</p>
    <p>Winnings will be delivered DIRECTLY to parents so <b>the survey must be completed by parents and legal guardians ONLY!</b></p>
</div>
</div>

{% endblock %}

mathtutor/templates/mathtutor/practice_item.html
{% extends 'mathtutor/base.html' %}
{% load staticfiles %}
{% block title %}{{ category.1 }}{% endblock %}
{% block content %}

<div class="col-md-8 col-md-pull-4">
<p>{{ learnItem.l_title }}</p>
{% if learnItem.l_type.name == 'vid' %}
	<iframe width="560" height="315" src="//www.youtube.com/embed/{{ learnItem.l_path }}?autoplay=1&rel=0" frameborder="0" allowfullscreen></iframe>

{% elif learnItem.l_type.name == 'def' %}
	<img src="{{ learnItem.get_file_path }}" style="width:435px;"/>

{% else %}
	<p>Tutorial Item</p>

{% endif %}
</div>
{% endblock %}

mathtutor/templates/mathtutor/practice_list.html
{% extends 'mathtutor/base.html' %}

{% block title %}{{ category.1 }}{% endblock %}
{% block content %}
<div class="col-md-8 col-md-pull-4">
<h3>{{ type_name }}</h3>
    {% for subCat in learnItems %}
        {{ subCat.0.l_sub.name }}
        {% for item in subCat %}
        <ul class="Thumb_{{ category.0.key }} nav nav-pills nav-stacked">
            <li>
            {% if item.l_type.name == 'tut' %}
            <a style="color: white;" href="http://byu.qualtrics.com/SE/?SID={{ item.l_path }}">{{ item.l_title }} <img src='/static/mathtutor/tutorials/{{ item.l_image }}.png' style="width:335px;"></a>
            {% else %}
			<a style="color: white;" href="{% url 'm:practice_item' category.0.key item.l_type.name item.id %}">{{ item.l_title }}</a>
			{% endif %}
			</li>

        </ul>
        {% endfor %}
    {% endfor %}
</div>
{% endblock %}

mathtutor/templates/mathtutor/quiz_or_practice.html
{% extends 'mathtutor/base.html' %}

{% block title %}{{ category.0.name }}{% endblock %}
{% block content %}

<div class="col-md-8 col-md-pull-4">
<!--<h3>Learning or Earning?</h3>-->
<div class="panel-group">
    <div class="panel panel-custom" id="earn">
        <div class="panel-heading panelHeading">
            <span class="panel-title" style="font-size: 1.3rem; font-weight: bold;">
                Click here to take a quiz to be on your way to the next level!
            </span>
        </div>
        <div class="panel-body panelBody" style="display:none;">
            <ul  class="nav nav-pills nav-stacked">
                <li>
                    <a href="{% url 'm:list_quizes' category.0.key %}">
                        Yes! Take me to the Quizzes page
                    </a>
                </li>
            </ul>
        </div>
    </div>

{% if user.student.group != 1 %}
    <div class="panel panel-custom" id="noearn">
        <div class="panel-heading panelHeading">
            <span class="panel-title">
            Want to brush up on the concepts?
            </span>
        </div>
        <div class="panel-body panelBody" style="display:none;">
            Yes! I want to learn from:
            {% if category.0.key != 'gen' and category.0.key != 'amc' %}
                <ul class="nav nav-pills nav-stacked">
                    {% for type in Constants.learnTypes %}
                    <li>
                        <a href="{% url 'm:practice' category.0.key type.key %}">{{ type.name }}</a>
                        </li>
                        {% endfor %}
                </ul>
                {% else %}
                <div class="panel-group">
                    {% for k,v in Constants.categories.items %}
                    {% if k == user.student.group %}
                    {% for row in v %}
            		{% if row.key != 'gen' and row.key != 'amc'  %}
                    <div class='panel panel-custom Thumb_{{ row.key }}' id="Thumb_{{ row.key }}">
                        <div class='panel-heading panelHeading'>
                            <span class='panel-title'>{{ row.name }}</span>
                        </div>
                        <div class='panel-body panelBody' style='display:none;'>
                            <ul class='nav nav-pills nav-stacked'>
                                {% for type in Constants.learnTypes %}
                                <li>
                                    <a href="{% url 'm:practice' row.key type.key %}">{{ type.name }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endif %}
                {% endfor %}
			    {% endif %}
                {% endfor %}
            </div>
            {% endif %}

        </div>
</div>
{% endif %}
</div>
</div>
{% endblock %}


<script type="text/javascript">
    $(function () { $('#collapseOne').collapse('show')});
</script>